name: Integrations Testing
on: 
  pull_request:
    branches:
      - sparsify.alpha # TODO: delete after merge
      - main
      - 'release/*'

jobs:
  integrations-test:
    runs-on: ubuntu-22.04
    env:
      SPARSEZOO_TEST_MODE: "true"
      SPARSIFY_EXTENSIVE_INTEGRATION_TEST: ""
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/checkout@v2
    - name: "⚙️ Install dependencies"
      run: pip3 install -e .[dev]
    - name: "⚙️ Logging into Sparsify"
      run: sparsify.login ${{ secrets.NM_SPARSIFY_TEST_API_KEY }}
    - name: "🔬 Running integrations tests (pre-commit)"
      run: make test_integration TARGETS=auto

